# Generated by Django 4.0.3 on 2022-04-04 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menstruation', '0002_rename_menstrualcycle_menstruation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menstruation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
