# Generated by Django 4.0.3 on 2022-04-05 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menstruation', '0004_alter_menstruation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menstruation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
